# Generated by Django 4.2 on 2025-02-20 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movie_go_be', '0001_initial'),
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
        ),
        migrations.AddField(
            model_name='seat',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studio'),
        ),
        migrations.AddField(
            model_name='reservedseat',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go_be.reservation'),
        ),
        migrations.AddField(
            model_name='reservedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go_be.seat'),
        ),
        migrations.AddField(
            model_name='reservedseat',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go_be.showtime'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go_be.showtime'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('movie', 'studio', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('studio', 'seat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='reservedseat',
            unique_together={('seat', 'showtime', 'reservation')},
        ),
    ]
