# Generated by Django 4.2 on 2025-02-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go_be', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seat',
            name='studio',
        ),
    ]
