# Generated by Django 4.2 on 2025-02-21 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
        ('movie_go_be', '0003_alter_seat_unique_together_remove_seat_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seats.seat'),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
