# Generated by Django 4.2 on 2025-02-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go_be', '0004_alter_reservedseat_seat_delete_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='studio',
        ),
    ]
