# Generated by Django 4.2 on 2025-02-21 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go_be', '0005_alter_showtime_unique_together_remove_showtime_movie_and_more'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtimes.showtime'),
        ),
        migrations.AlterField(
            model_name='reservedseat',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showtimes.showtime'),
        ),
        migrations.DeleteModel(
            name='Showtime',
        ),
    ]
