# Generated by Django 4.2 on 2025-02-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go_be', '0006_alter_reservation_showtime_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservedseat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservedseat',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservedseat',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='reservedseat',
            name='showtime',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservedSeat',
        ),
    ]
